import type { BuildingDef, BuildingType } from '@/types';

const scaling = {
  hpPerLevel: 0.2,
  outputPerLevel: 0.22,
  upgradeBaseCost: { wood: 30, scrap: 20 },
  costGrowth: 1.38,
};

export const BUILDINGS: Record<BuildingType, BuildingDef> = {
  shelter: {
    type: 'shelter',
    name: 'Ратуша',
    category: 'core',
    size: { w: 3, h: 3 },
    maxLevel: 10,
    baseHp: 1600,
    buildCost: {},
    scaling: {
      hpPerLevel: 0.25,
      outputPerLevel: 0.2,
      upgradeBaseCost: { wood: 120, scrap: 120, energy: 40 },
      costGrowth: 1.5,
    },
    description: 'Главное здание базы. Повышает лимиты ресурсов.',
  },

  tower: {
    type: 'tower',
    name: 'Башня',
    category: 'defense',
    size: { w: 1, h: 1 },
    maxLevel: 8,
    baseHp: 260,
    buildCost: { wood: 35, scrap: 10 },
    baseDamage: 0,
    fireRate: 1,
    range: 220,
    scaling: {
      hpPerLevel: 0.2,
      outputPerLevel: 0.16,
      upgradeBaseCost: { wood: 28, scrap: 30 },
      costGrowth: 1.4,
    },
    description: 'Оборонительная башня с вращающимся стволом.',
  },

  wall: {
    type: 'wall',
    name: 'Стена',
    category: 'barrier',
    size: { w: 1, h: 1 },
    maxLevel: 10,
    baseHp: 320,
    buildCost: { wood: 8 },
    scaling: {
      hpPerLevel: 0.3,
      outputPerLevel: 0,
      upgradeBaseCost: { wood: 10, scrap: 12 },
      costGrowth: 1.35,
    },
    description: 'Сегмент обороны, стыкуется с соседними стенами.',
  },

  gate: {
    type: 'gate',
    name: 'Ворота',
    category: 'barrier',
    size: { w: 2, h: 1 },
    maxLevel: 5,
    baseHp: 650,
    buildCost: { wood: 35, scrap: 20 },
    scaling,
    description: 'Проход через стену. Можно открывать и закрывать.',
  },

  barracks: {
    type: 'barracks',
    name: 'Казармы',
    category: 'support',
    size: { w: 2, h: 2 },
    maxLevel: 5,
    baseHp: 520,
    buildCost: { wood: 55 },
    scaling: {
      hpPerLevel: 0.2,
      outputPerLevel: 0.25,
      upgradeBaseCost: { wood: 45, scrap: 55, food: 25 },
      costGrowth: 1.45,
    },
    description: 'Производство и размещение бойцов гарнизона.',
  },

  trainingGround: {
    type: 'trainingGround',
    name: 'Полигон',
    category: 'support',
    size: { w: 2, h: 2 },
    maxLevel: 5,
    baseHp: 420,
    buildCost: { wood: 45, food: 15 },
    scaling: {
      hpPerLevel: 0.18,
      outputPerLevel: 0.28,
      upgradeBaseCost: { wood: 38, scrap: 45, food: 25 },
      costGrowth: 1.42,
    },
    description: 'Тренировка и прокачка защитников.',
  },

  storage: {
    type: 'storage',
    name: 'Склад',
    category: 'production',
    size: { w: 2, h: 2 },
    maxLevel: 6,
    baseHp: 520,
    buildCost: { wood: 45 },
    produces: 'wood',
    productionRate: 0.5,
    scaling: {
      hpPerLevel: 0.2,
      outputPerLevel: 0.25,
      upgradeBaseCost: { wood: 40, scrap: 35 },
      costGrowth: 1.42,
    },
    description: 'Хранилище дерева и базовых припасов.',
  },

  workshop: {
    type: 'workshop',
    name: 'Кузница',
    category: 'production',
    size: { w: 2, h: 2 },
    maxLevel: 6,
    baseHp: 430,
    buildCost: { wood: 65, scrap: 15 },
    produces: 'scrap',
    productionRate: 2.5,
    scaling: {
      hpPerLevel: 0.2,
      outputPerLevel: 0.3,
      upgradeBaseCost: { wood: 35, scrap: 70, energy: 10 },
      costGrowth: 1.45,
    },
    description: 'Кует металл и детали для обороны.',
  },

  fuelDepot: {
    type: 'fuelDepot',
    name: 'Склад топлива',
    category: 'production',
    size: { w: 1, h: 2 },
    maxLevel: 6,
    baseHp: 300,
    buildCost: { scrap: 90 },
    produces: 'fuel',
    productionRate: 1.8,
    scaling,
    description: 'Хранит топливо для поздних построек.',
  },

  garden: {
    type: 'garden',
    name: 'Огород',
    category: 'production',
    size: { w: 2, h: 1 },
    maxLevel: 4,
    baseHp: 220,
    buildCost: { wood: 30 },
    produces: 'food',
    productionRate: 2,
    scaling,
    description: 'Источник еды для долгой обороны.',
  },

  researchCenter: {
    type: 'researchCenter',
    name: 'Совет',
    category: 'support',
    size: { w: 2, h: 2 },
    maxLevel: 5,
    baseHp: 360,
    buildCost: { scrap: 160, energy: 30 },
    scaling,
    description: 'Открывает новые технологии.',
  },

  generator: {
    type: 'generator',
    name: 'Генератор',
    category: 'production',
    size: { w: 1, h: 1 },
    maxLevel: 5,
    baseHp: 250,
    buildCost: { scrap: 110, fuel: 30 },
    produces: 'energy',
    productionRate: 1.5,
    scaling,
    description: 'Даёт энергию для продвинутой обороны.',
  },

  medbay: {
    type: 'medbay',
    name: 'Лазарет',
    category: 'support',
    size: { w: 1, h: 1 },
    maxLevel: 4,
    baseHp: 250,
    buildCost: { scrap: 90, food: 30 },
    scaling,
    description: 'Помогает восстановиться после ночи.',
  },

  sniperNest: {
    type: 'sniperNest',
    name: 'Дозор',
    category: 'defense',
    size: { w: 1, h: 1 },
    maxLevel: 6,
    baseHp: 190,
    buildCost: { scrap: 130, fuel: 20 },
    baseDamage: 120,
    fireRate: 0.4,
    range: 420,
    scaling,
    description: 'Дальний огонь по приоритетным целям.',
  },

  mortar: {
    type: 'mortar',
    name: 'Миномет',
    category: 'defense',
    size: { w: 2, h: 1 },
    maxLevel: 5,
    baseHp: 240,
    buildCost: { scrap: 160, fuel: 40, energy: 20 },
    baseDamage: 90,
    fireRate: 0.3,
    range: 380,
    aoeRadius: 80,
    scaling,
    description: 'Бьет по площади и сдерживает плотные волны.',
  },

  electricFence: {
    type: 'electricFence',
    name: 'Электрозаграждение',
    category: 'defense',
    size: { w: 1, h: 1 },
    maxLevel: 4,
    baseHp: 170,
    buildCost: { scrap: 100, energy: 50 },
    baseDamage: 25,
    fireRate: 2,
    range: 90,
    aoeRadius: 90,
    scaling,
    description: 'Поздняя линия обороны для ближнего контакта.',
  },
};

export const STARTER_BUILDINGS: BuildingType[] = [
  'tower',
  'wall',
  'barracks',
  'trainingGround',
  'storage',
  'workshop',
];

export const BUILDING_LIST: BuildingDef[] = Object.values(BUILDINGS);
