/**
 * The technology tree — three branches (weapons / fortification / survival),
 * each six tiers plus a capstone doctrine. Mirrors the design spec.
 */

import type { ResearchNode } from '@/types';

export const RESEARCH: ResearchNode[] = [
  // -------------------------------------------------------------------------
  // WEAPONS 🔫
  // -------------------------------------------------------------------------
  {
    id: 'wpn1',
    branch: 'weapons',
    tier: 1,
    name: 'Примитивное Оружие',
    description: 'Стартовое знание. Палки, копья, луки.',
    prerequisites: [],
    cost: {},
    days: 0,
    effects: [{ kind: 'unlockWeaponBranch', branch: 'primitive' }],
  },
  {
    id: 'wpn2',
    branch: 'weapons',
    tier: 2,
    name: 'Порох',
    description: 'Открывает ветку Огнестрела.',
    prerequisites: ['wpn1'],
    cost: { scrap: 120, fuel: 40 },
    days: 2,
    effects: [{ kind: 'unlockWeaponBranch', branch: 'firearm' }],
  },
  {
    id: 'wpn3',
    branch: 'weapons',
    tier: 3,
    name: 'Массовое Производство Патронов',
    description: '−30% стоимость патронов.',
    prerequisites: ['wpn2'],
    cost: { scrap: 200, fuel: 60 },
    days: 2,
    effects: [{ kind: 'modifier', stat: 'ammoCost', mult: 0.7 }],
  },
  {
    id: 'wpn4',
    branch: 'weapons',
    tier: 4,
    name: 'Автоматическое Оружие',
    description: 'Открывает автоматы.',
    prerequisites: ['wpn3'],
    cost: { scrap: 280, fuel: 80, energy: 30 },
    days: 3,
    effects: [{ kind: 'modifier', stat: 'autoWeapons', mult: 1 }],
  },
  {
    id: 'wpn5',
    branch: 'weapons',
    tier: 5,
    name: 'Тяжёлое Вооружение',
    description: 'Открывает РПГ и миниган.',
    prerequisites: ['wpn4'],
    cost: { scrap: 400, energy: 120 },
    days: 4,
    effects: [{ kind: 'unlockWeaponBranch', branch: 'heavy' }],
  },
  {
    id: 'wpn6',
    branch: 'weapons',
    tier: 6,
    name: 'Экспериментальное Оружие',
    description: 'Открывает электро и плазму.',
    prerequisites: ['wpn5'],
    cost: { scrap: 560, energy: 220 },
    days: 5,
    effects: [{ kind: 'modifier', stat: 'experimentalWeapons', mult: 1 }],
  },
  {
    id: 'wpnDoctrine',
    branch: 'weapons',
    tier: 7,
    name: 'Доктрина «Огневое Превосходство»',
    description: 'Все башни +25% урон, +15% скорострельность.',
    prerequisites: ['wpn6'],
    cost: { scrap: 700, energy: 260 },
    days: 6,
    isDoctrine: true,
    effects: [
      { kind: 'modifier', stat: 'towerDamage', mult: 1.25 },
      { kind: 'modifier', stat: 'towerFireRate', mult: 1.15 },
      { kind: 'doctrine', name: 'Огневое Превосходство', description: 'Башни доминируют на поле.' },
    ],
  },

  // -------------------------------------------------------------------------
  // FORTIFICATION 🧱
  // -------------------------------------------------------------------------
  {
    id: 'fort1',
    branch: 'fortification',
    tier: 1,
    name: 'Деревянные Стены',
    description: 'Стартовое знание фортификации.',
    prerequisites: [],
    cost: {},
    days: 0,
    effects: [{ kind: 'unlockBuilding', building: 'wall' }],
  },
  {
    id: 'fort2',
    branch: 'fortification',
    tier: 2,
    name: 'Каменные Стены',
    description: 'Стены +100% HP.',
    prerequisites: ['fort1'],
    cost: { scrap: 160 },
    days: 2,
    effects: [{ kind: 'modifier', stat: 'wallHp', mult: 2 }],
  },
  {
    id: 'fort3',
    branch: 'fortification',
    tier: 3,
    name: 'Противопехотные Мины',
    description: 'Новое здание — Мина.',
    prerequisites: ['fort2'],
    cost: { scrap: 220, fuel: 60 },
    days: 2,
    effects: [{ kind: 'modifier', stat: 'mines', mult: 1 }],
  },
  {
    id: 'fort4',
    branch: 'fortification',
    tier: 4,
    name: 'Бетонные Укрепления',
    description: 'Стены +200% HP, замедляют зомби при ударе.',
    prerequisites: ['fort3'],
    cost: { scrap: 340, energy: 60 },
    days: 3,
    effects: [
      { kind: 'modifier', stat: 'wallHp', mult: 3 },
      { kind: 'modifier', stat: 'wallSlow', mult: 1 },
    ],
  },
  {
    id: 'fort5',
    branch: 'fortification',
    tier: 5,
    name: 'Электрифицированные Заграждения',
    description: 'Открывает Электрозаграждение.',
    prerequisites: ['fort4'],
    cost: { scrap: 420, energy: 160 },
    days: 4,
    effects: [{ kind: 'unlockBuilding', building: 'electricFence' }],
  },
  {
    id: 'fort6',
    branch: 'fortification',
    tier: 6,
    name: 'Бункерная Архитектура',
    description: 'Убежище получает броню, −50% входящий урон.',
    prerequisites: ['fort5'],
    cost: { scrap: 600, energy: 200 },
    days: 5,
    effects: [{ kind: 'modifier', stat: 'shelterArmor', mult: 0.5 }],
  },
  {
    id: 'fortDoctrine',
    branch: 'fortification',
    tier: 7,
    name: 'Доктрина «Неприступная Крепость»',
    description: 'Здания восстанавливают 2% HP/сек вне боя.',
    prerequisites: ['fort6'],
    cost: { scrap: 720, energy: 240 },
    days: 6,
    isDoctrine: true,
    effects: [
      { kind: 'modifier', stat: 'buildingRegen', mult: 0.02 },
      { kind: 'doctrine', name: 'Неприступная Крепость', description: 'База залечивает раны сама.' },
    ],
  },

  // -------------------------------------------------------------------------
  // SURVIVAL 🌿
  // -------------------------------------------------------------------------
  {
    id: 'surv1',
    branch: 'survival',
    tier: 1,
    name: 'Базовое Собирательство',
    description: 'Стартовое знание выживания.',
    prerequisites: [],
    cost: {},
    days: 0,
    effects: [{ kind: 'modifier', stat: 'gathering', mult: 1 }],
  },
  {
    id: 'surv2',
    branch: 'survival',
    tier: 2,
    name: 'Организованное Производство',
    description: 'Все здания +20% производительность.',
    prerequisites: ['surv1'],
    cost: { scrap: 140, food: 40 },
    days: 2,
    effects: [{ kind: 'modifier', stat: 'production', mult: 1.2 }],
  },
  {
    id: 'surv3',
    branch: 'survival',
    tier: 3,
    name: 'Военная Логистика',
    description: '+25% лимит всех ресурсов.',
    prerequisites: ['surv2'],
    cost: { scrap: 220, food: 60 },
    days: 2,
    effects: [{ kind: 'modifier', stat: 'resourceCap', mult: 1.25 }],
  },
  {
    id: 'surv4',
    branch: 'survival',
    tier: 4,
    name: 'Медицина Выживания',
    description: 'Медпункт работает во время ночи.',
    prerequisites: ['surv3'],
    cost: { scrap: 280, food: 80, energy: 40 },
    days: 3,
    effects: [{ kind: 'modifier', stat: 'medbayNight', mult: 1 }],
  },
  {
    id: 'surv5',
    branch: 'survival',
    tier: 5,
    name: 'Казармы Элиты',
    description: 'Солдаты +50% урон и HP.',
    prerequisites: ['surv4'],
    cost: { scrap: 380, food: 120 },
    days: 4,
    effects: [
      { kind: 'modifier', stat: 'soldierDamage', mult: 1.5 },
      { kind: 'modifier', stat: 'soldierHp', mult: 1.5 },
    ],
  },
  {
    id: 'surv6',
    branch: 'survival',
    tier: 6,
    name: 'Экономика Войны',
    description: 'Каждая пережитая ночь даёт +10% ресурсов.',
    prerequisites: ['surv5'],
    cost: { scrap: 520, food: 160, energy: 80 },
    days: 5,
    effects: [{ kind: 'modifier', stat: 'nightBonus', mult: 1.1 }],
  },
  {
    id: 'survDoctrine',
    branch: 'survival',
    tier: 7,
    name: 'Доктрина «Люди — Последний Ресурс»',
    description: 'При смерти игрок возрождается с 50% HP без штрафа.',
    prerequisites: ['surv6'],
    cost: { scrap: 700, food: 200 },
    days: 6,
    isDoctrine: true,
    effects: [
      { kind: 'modifier', stat: 'freeRevive', mult: 1 },
      { kind: 'doctrine', name: 'Люди — Последний Ресурс', description: 'Смерть — не конец, пока стоит база.' },
    ],
  },
];

/** Research nodes unlocked for free at the start of a run. */
export const STARTER_RESEARCH: string[] = ['wpn1', 'fort1', 'surv1'];

export function researchById(id: string): ResearchNode | undefined {
  return RESEARCH.find((r) => r.id === id);
}
