/**
 * The weapon tree — shared progression for the player character and towers.
 * Three branches: primitive, firearm, heavy. Prerequisites encode the tree
 * shape from the design spec.
 */

import type { WeaponDef, WeaponId } from '@/types';

export const WEAPONS: Record<WeaponId, WeaponDef> = {
  // -------------------------------------------------------------------------
  // PRIMITIVE
  // -------------------------------------------------------------------------
  sharpenedStick: {
    id: 'sharpenedStick',
    name: 'Заточенная Палка',
    branch: 'primitive',
    prerequisites: [],
    behavior: 'single',
    damage: 14,
    fireRate: 1.6,
    range: 60,
    projectileSpeed: 0,
    magazine: 0, // melee, no reload
    reloadTime: 0,
    purchaseCost: {},
    upgradeBaseCost: { scrap: 20 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'shove',
      name: 'Толчок',
      description: 'Отталкивает врагов в конусе перед собой.',
      cooldown: 12,
      duration: 0,
    },
  },
  spear: {
    id: 'spear',
    name: 'Копьё',
    branch: 'primitive',
    prerequisites: ['sharpenedStick'],
    behavior: 'single',
    damage: 21,
    fireRate: 1.4,
    range: 84,
    projectileSpeed: 0,
    magazine: 0,
    reloadTime: 0,
    purchaseCost: { scrap: 40 },
    upgradeBaseCost: { scrap: 30 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'lunge',
      name: 'Выпад',
      description: 'Рывок вперёд, пронзая всех на линии.',
      cooldown: 14,
      duration: 0,
    },
  },
  compositeSpear: {
    id: 'compositeSpear',
    name: 'Составное Копьё',
    branch: 'primitive',
    prerequisites: ['spear'],
    behavior: 'piercing',
    damage: 26,
    fireRate: 1.4,
    range: 96,
    projectileSpeed: 0,
    magazine: 0,
    reloadTime: 0,
    pierceCount: 2,
    purchaseCost: { scrap: 80 },
    upgradeBaseCost: { scrap: 50 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'whirl',
      name: 'Вихрь',
      description: 'Круговой удар по всем вокруг.',
      cooldown: 16,
      duration: 0,
    },
  },
  makeshiftBow: {
    id: 'makeshiftBow',
    name: 'Самодельный Лук',
    branch: 'primitive',
    prerequisites: [],
    behavior: 'single',
    damage: 18,
    fireRate: 1.1,
    range: 260,
    projectileSpeed: 320,
    magazine: 1,
    reloadTime: 0.8,
    purchaseCost: { scrap: 30 },
    upgradeBaseCost: { scrap: 25 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'volley',
      name: 'Залп',
      description: 'Выпускает веер из 5 стрел.',
      cooldown: 15,
      duration: 0,
    },
  },
  reinforcedBow: {
    id: 'reinforcedBow',
    name: 'Усиленный Лук',
    branch: 'primitive',
    prerequisites: ['makeshiftBow'],
    behavior: 'single',
    damage: 24,
    fireRate: 1.2,
    range: 280,
    projectileSpeed: 450,
    magazine: 1,
    reloadTime: 0.7,
    purchaseCost: { scrap: 70 },
    upgradeBaseCost: { scrap: 45 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'volley',
      name: 'Залп',
      description: 'Выпускает веер из 6 стрел.',
      cooldown: 14,
      duration: 0,
    },
  },
  crossbow: {
    id: 'crossbow',
    name: 'Арбалет',
    branch: 'primitive',
    prerequisites: ['reinforcedBow'],
    behavior: 'piercing',
    damage: 48,
    fireRate: 0.8,
    range: 300,
    projectileSpeed: 520,
    magazine: 1,
    reloadTime: 1.4,
    pierceCount: 2,
    purchaseCost: { scrap: 120 },
    upgradeBaseCost: { scrap: 70 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'pin',
      name: 'Пригвоздить',
      description: 'Тяжёлый болт, обездвиживает цель на 3 сек.',
      cooldown: 16,
      duration: 3,
    },
  },
  compositeCrossbow: {
    id: 'compositeCrossbow',
    name: 'Составной Арбалет',
    branch: 'primitive',
    prerequisites: ['crossbow'],
    behavior: 'piercing',
    damage: 52,
    fireRate: 1.2,
    range: 320,
    projectileSpeed: 600,
    magazine: 1,
    reloadTime: 1.1,
    pierceCount: 3,
    purchaseCost: { scrap: 200 },
    upgradeBaseCost: { scrap: 110 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'pin',
      name: 'Пригвоздить',
      description: 'Тяжёлый болт, обездвиживает цель на 4 сек.',
      cooldown: 14,
      duration: 4,
    },
  },

  // -------------------------------------------------------------------------
  // FIREARM (requires fuel + scrap; consumes ammo)
  // -------------------------------------------------------------------------
  makeshiftPistol: {
    id: 'makeshiftPistol',
    name: 'Самодельный Пистолет',
    branch: 'firearm',
    prerequisites: [],
    behavior: 'single',
    damage: 28,
    fireRate: 2.2,
    range: 240,
    projectileSpeed: 700,
    magazine: 8,
    reloadTime: 1.4,
    consumes: 'ammo',
    purchaseCost: { scrap: 90, fuel: 30 },
    upgradeBaseCost: { scrap: 60, fuel: 20 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'fanfire',
      name: 'Веер выстрелов',
      description: 'Разряжает магазин очень быстро.',
      cooldown: 18,
      duration: 2,
    },
  },
  pistol9mm: {
    id: 'pistol9mm',
    name: 'Пистолет 9мм',
    branch: 'firearm',
    prerequisites: ['makeshiftPistol'],
    behavior: 'single',
    damage: 36,
    fireRate: 2.6,
    range: 260,
    projectileSpeed: 760,
    magazine: 16,
    reloadTime: 1.3,
    consumes: 'ammo',
    purchaseCost: { scrap: 140, fuel: 40 },
    upgradeBaseCost: { scrap: 80, fuel: 25 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'fanfire',
      name: 'Веер выстрелов',
      description: 'Разряжает магазин очень быстро.',
      cooldown: 16,
      duration: 2,
    },
  },
  dualPistols: {
    id: 'dualPistols',
    name: 'Двойные Пистолеты',
    branch: 'firearm',
    prerequisites: ['pistol9mm'],
    behavior: 'single',
    damage: 36,
    fireRate: 5.2,
    range: 250,
    projectileSpeed: 760,
    magazine: 32,
    reloadTime: 1.8,
    consumes: 'ammo',
    purchaseCost: { scrap: 220, fuel: 60 },
    upgradeBaseCost: { scrap: 120, fuel: 35 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'akimboStorm',
      name: 'Шторм',
      description: 'Двойная скорострельность 4 сек.',
      cooldown: 20,
      duration: 4,
    },
  },
  smg: {
    id: 'smg',
    name: 'Пистолет-пулемёт',
    branch: 'firearm',
    prerequisites: ['pistol9mm'],
    behavior: 'single',
    damage: 22,
    fireRate: 9,
    range: 240,
    projectileSpeed: 780,
    magazine: 30,
    reloadTime: 1.8,
    spread: 0.12,
    consumes: 'ammo',
    purchaseCost: { scrap: 240, fuel: 70 },
    upgradeBaseCost: { scrap: 130, fuel: 40 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'suppress',
      name: 'Подавление',
      description: '×2 скорострельность, +точность 4 сек.',
      cooldown: 20,
      duration: 4,
    },
  },
  sawnoff: {
    id: 'sawnoff',
    name: 'Обрез',
    branch: 'firearm',
    prerequisites: [],
    behavior: 'cone',
    damage: 16, // per pellet
    fireRate: 1.1,
    range: 160,
    projectileSpeed: 680,
    magazine: 2,
    reloadTime: 1.8,
    spread: 0.4,
    consumes: 'ammo',
    purchaseCost: { scrap: 110, fuel: 30 },
    upgradeBaseCost: { scrap: 70, fuel: 20 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'bothBarrels',
      name: 'Оба ствола',
      description: 'Двойной залп в упор.',
      cooldown: 14,
      duration: 0,
    },
  },
  pumpShotgun: {
    id: 'pumpShotgun',
    name: 'Помповый Дробовик',
    branch: 'firearm',
    prerequisites: ['sawnoff'],
    behavior: 'cone',
    damage: 18,
    fireRate: 1.0,
    range: 200,
    projectileSpeed: 700,
    magazine: 6,
    reloadTime: 2.4,
    spread: 0.35,
    consumes: 'ammo',
    purchaseCost: { scrap: 180, fuel: 50 },
    upgradeBaseCost: { scrap: 100, fuel: 30 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'slug',
      name: 'Пуля-слаг',
      description: 'Один мощный пробивающий выстрел.',
      cooldown: 16,
      duration: 0,
    },
  },
  autoShotgun: {
    id: 'autoShotgun',
    name: 'Автодробовик',
    branch: 'firearm',
    prerequisites: ['pumpShotgun'],
    behavior: 'cone',
    damage: 16,
    fireRate: 2.4,
    range: 200,
    projectileSpeed: 720,
    magazine: 8,
    reloadTime: 2.6,
    spread: 0.38,
    consumes: 'ammo',
    purchaseCost: { scrap: 280, fuel: 80 },
    upgradeBaseCost: { scrap: 150, fuel: 45 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'fullAuto',
      name: 'Шквал',
      description: 'Опустошает магазин веером.',
      cooldown: 18,
      duration: 2,
    },
  },
  tacticalShotgun: {
    id: 'tacticalShotgun',
    name: 'Тактический Дробовик',
    branch: 'firearm',
    prerequisites: ['autoShotgun'],
    behavior: 'cone',
    damage: 29,
    fireRate: 2.6,
    range: 220,
    projectileSpeed: 760,
    magazine: 10,
    reloadTime: 2.2,
    spread: 0.32,
    consumes: 'ammo',
    purchaseCost: { scrap: 380, fuel: 110 },
    upgradeBaseCost: { scrap: 200, fuel: 60 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'breach',
      name: 'Пролом',
      description: 'Концентрированный залп, оглушает в конусе.',
      cooldown: 18,
      duration: 0,
    },
  },
  ak: {
    id: 'ak',
    name: 'Автомат АК',
    branch: 'firearm',
    prerequisites: ['smg'],
    behavior: 'single',
    damage: 34,
    fireRate: 8,
    range: 300,
    projectileSpeed: 900,
    magazine: 30,
    reloadTime: 2.2,
    spread: 0.1,
    consumes: 'ammo',
    purchaseCost: { scrap: 360, fuel: 100 },
    upgradeBaseCost: { scrap: 190, fuel: 55 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'suppressingFire',
      name: 'Режим шквального огня',
      description: '×3 скорострельность 5 сек.',
      cooldown: 22,
      duration: 5,
    },
  },
  m4: {
    id: 'm4',
    name: 'Штурмовая Винтовка M4',
    branch: 'firearm',
    prerequisites: ['ak'],
    behavior: 'single',
    damage: 38,
    fireRate: 9.5,
    range: 340,
    projectileSpeed: 1000,
    magazine: 30,
    reloadTime: 2.0,
    spread: 0.05,
    consumes: 'ammo',
    purchaseCost: { scrap: 480, fuel: 140 },
    upgradeBaseCost: { scrap: 240, fuel: 70 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'suppressingFire',
      name: 'Режим шквального огня',
      description: '×3 скорострельность 5 сек.',
      cooldown: 20,
      duration: 5,
    },
  },
  battleRifle: {
    id: 'battleRifle',
    name: 'Боевая Винтовка',
    branch: 'firearm',
    prerequisites: ['m4'],
    behavior: 'piercing',
    damage: 95,
    fireRate: 3.5,
    range: 380,
    projectileSpeed: 1100,
    magazine: 20,
    reloadTime: 2.2,
    pierceCount: 2,
    spread: 0.02,
    consumes: 'ammo',
    purchaseCost: { scrap: 620, fuel: 180 },
    upgradeBaseCost: { scrap: 300, fuel: 90 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'marksman',
      name: 'Точный бой',
      description: 'Каждый выстрел пробивает всех на линии 5 сек.',
      cooldown: 22,
      duration: 5,
    },
  },
  makeshiftSniper: {
    id: 'makeshiftSniper',
    name: 'Самодельная Снайперка',
    branch: 'firearm',
    prerequisites: ['sawnoff'],
    behavior: 'piercing',
    damage: 140,
    fireRate: 0.6,
    range: 520,
    projectileSpeed: 1400,
    magazine: 4,
    reloadTime: 2.6,
    pierceCount: 2,
    consumes: 'ammo',
    purchaseCost: { scrap: 300, fuel: 80 },
    upgradeBaseCost: { scrap: 160, fuel: 45 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'focus',
      name: 'Фокус',
      description: 'Следующий выстрел ×3 урон, мгновенный.',
      cooldown: 18,
      duration: 0,
    },
  },
  sniperRifle: {
    id: 'sniperRifle',
    name: 'Снайперская Винтовка',
    branch: 'firearm',
    prerequisites: ['makeshiftSniper'],
    behavior: 'piercing',
    damage: 240,
    fireRate: 0.7,
    range: 700,
    projectileSpeed: 1700,
    magazine: 5,
    reloadTime: 2.8,
    pierceCount: 3,
    consumes: 'ammo',
    purchaseCost: { scrap: 520, fuel: 150 },
    upgradeBaseCost: { scrap: 260, fuel: 80 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'penetrator',
      name: 'Пробитие',
      description: 'Выстрел сквозь стены и любую броню.',
      cooldown: 20,
      duration: 0,
    },
  },
  fiftyCal: {
    id: 'fiftyCal',
    name: '.50 Cal',
    branch: 'firearm',
    prerequisites: ['sniperRifle'],
    behavior: 'piercing',
    damage: 600,
    fireRate: 0.5,
    range: 800,
    projectileSpeed: 2000,
    magazine: 5,
    reloadTime: 3.2,
    pierceCount: 5,
    consumes: 'ammo',
    purchaseCost: { scrap: 760, fuel: 220 },
    upgradeBaseCost: { scrap: 380, fuel: 120 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'executioner',
      name: 'Палач',
      description: 'Мгновенно убивает обычных зомби на линии.',
      cooldown: 24,
      duration: 0,
    },
  },

  // -------------------------------------------------------------------------
  // HEAVY (requires energy + scrap; consumes rockets/components)
  // -------------------------------------------------------------------------
  rpg7: {
    id: 'rpg7',
    name: 'РПГ-7',
    branch: 'heavy',
    prerequisites: [],
    behavior: 'explosive',
    damage: 400,
    fireRate: 0.4,
    range: 420,
    projectileSpeed: 520,
    magazine: 1,
    reloadTime: 3.4,
    effectRadius: 110,
    consumes: 'rockets',
    purchaseCost: { scrap: 500, energy: 120 },
    upgradeBaseCost: { scrap: 260, energy: 70 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'barrage',
      name: 'Залп',
      description: 'Три ракеты подряд без перезарядки.',
      cooldown: 26,
      duration: 0,
    },
  },
  antiTankLauncher: {
    id: 'antiTankLauncher',
    name: 'Противотанковый Ракетомёт',
    branch: 'heavy',
    prerequisites: ['rpg7'],
    behavior: 'explosive',
    damage: 650,
    fireRate: 0.5,
    range: 480,
    projectileSpeed: 600,
    magazine: 2,
    reloadTime: 3.8,
    effectRadius: 130,
    consumes: 'rockets',
    purchaseCost: { scrap: 760, energy: 200 },
    upgradeBaseCost: { scrap: 380, energy: 110 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'lockOn',
      name: 'Захват цели',
      description: 'Самонаводящиеся ракеты 6 сек.',
      cooldown: 28,
      duration: 6,
    },
  },
  minigun: {
    id: 'minigun',
    name: 'Миниган',
    branch: 'heavy',
    prerequisites: [],
    behavior: 'single',
    damage: 30,
    fireRate: 18,
    range: 320,
    projectileSpeed: 950,
    magazine: 200,
    reloadTime: 5,
    spread: 0.14,
    consumes: 'ammo',
    purchaseCost: { scrap: 560, energy: 140 },
    upgradeBaseCost: { scrap: 280, energy: 80 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'spinUp',
      name: 'Раскрутка',
      description: 'Мгновенно на максимум, не перегревается 5 сек.',
      cooldown: 26,
      duration: 5,
    },
  },
  aircraftMinigun: {
    id: 'aircraftMinigun',
    name: 'Авиационный Миниган',
    branch: 'heavy',
    prerequisites: ['minigun'],
    behavior: 'single',
    damage: 60,
    fireRate: 20,
    range: 340,
    projectileSpeed: 1000,
    magazine: 300,
    reloadTime: 5.5,
    spread: 0.12,
    consumes: 'ammo',
    purchaseCost: { scrap: 820, energy: 220 },
    upgradeBaseCost: { scrap: 410, energy: 130 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'spinUp',
      name: 'Раскрутка',
      description: 'Мгновенно на максимум, не перегревается 7 сек.',
      cooldown: 24,
      duration: 7,
    },
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'Огнемёт',
    branch: 'heavy',
    prerequisites: [],
    behavior: 'beam',
    damage: 40, // per second to targets in the cone
    fireRate: 1, // continuous
    range: 180,
    projectileSpeed: 0,
    magazine: 100, // fuel units
    reloadTime: 3,
    spread: 0.3,
    effectRadius: 0,
    consumes: 'ammo',
    purchaseCost: { scrap: 480, energy: 100 },
    upgradeBaseCost: { scrap: 240, energy: 60 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'fireWall',
      name: 'Огненная стена',
      description: 'Оставляет горящую полосу на 5 сек.',
      cooldown: 22,
      duration: 5,
    },
  },
  thermobaricFlamethrower: {
    id: 'thermobaricFlamethrower',
    name: 'Термобарический Огнемёт',
    branch: 'heavy',
    prerequisites: ['flamethrower'],
    behavior: 'beam',
    damage: 70,
    fireRate: 1,
    range: 200,
    projectileSpeed: 0,
    magazine: 120,
    reloadTime: 3.2,
    spread: 0.32,
    effectRadius: 100,
    consumes: 'ammo',
    purchaseCost: { scrap: 760, energy: 180 },
    upgradeBaseCost: { scrap: 380, energy: 110 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'detonate',
      name: 'Взрывной выброс',
      description: 'Поджигает воздух — взрыв в конусе.',
      cooldown: 24,
      duration: 0,
    },
  },
  electricCannon: {
    id: 'electricCannon',
    name: 'Электрическая Пушка',
    branch: 'heavy',
    prerequisites: [],
    behavior: 'chain',
    damage: 90,
    fireRate: 1.5,
    range: 300,
    projectileSpeed: 0, // instant arc
    magazine: 20,
    reloadTime: 2.6,
    chainCount: 5,
    consumes: 'advancedComponents',
    purchaseCost: { scrap: 540, energy: 160 },
    upgradeBaseCost: { scrap: 270, energy: 90 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'overload',
      name: 'Перегрузка',
      description: 'Молния бьёт по всем в радиусе.',
      cooldown: 24,
      duration: 0,
    },
  },
  plasmaCannon: {
    id: 'plasmaCannon',
    name: 'Плазменная Пушка',
    branch: 'heavy',
    prerequisites: ['electricCannon'],
    behavior: 'explosive',
    damage: 320,
    fireRate: 1.2,
    range: 360,
    projectileSpeed: 640,
    magazine: 12,
    reloadTime: 3,
    effectRadius: 120,
    consumes: 'advancedComponents',
    purchaseCost: { scrap: 880, energy: 260 },
    upgradeBaseCost: { scrap: 440, energy: 150 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'novaball',
      name: 'Сфера Новы',
      description: 'Огромный плазменный шар, цепной взрыв.',
      cooldown: 28,
      duration: 0,
    },
  },

  // ---------------------------------------------------------------------------
  // PREMIUM (shop-exclusive, bought with crystals — no research prerequisites)
  // ---------------------------------------------------------------------------
  goldenMinigun: {
    id: 'goldenMinigun',
    name: 'Золотой Миниган',
    branch: 'heavy',
    premium: true,
    prerequisites: [],
    behavior: 'single',
    damage: 75,
    fireRate: 22,
    range: 360,
    projectileSpeed: 1000,
    magazine: 300,
    reloadTime: 3.6,
    spread: 0.1,
    consumes: 'ammo',
    purchaseCost: {},
    upgradeBaseCost: { scrap: 300, energy: 90 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'midasRage',
      name: 'Ярость Мидаса',
      description: 'Двойной урон и бесконечный магазин 6 сек.',
      cooldown: 24,
      duration: 6,
    },
  },
  infernoMinigun: {
    id: 'infernoMinigun',
    name: 'Адский Миниган',
    branch: 'heavy',
    premium: true,
    prerequisites: [],
    behavior: 'piercing',
    pierceCount: 2,
    damage: 58,
    fireRate: 24,
    range: 340,
    projectileSpeed: 980,
    magazine: 260,
    reloadTime: 4,
    spread: 0.12,
    consumes: 'ammo',
    purchaseCost: {},
    upgradeBaseCost: { scrap: 320, energy: 100 },
    costGrowth: 1.5,
    maxLevel: 5,
    ability: {
      id: 'hellStorm',
      name: 'Огненный Шторм',
      description: 'Пули поджигают всё на своём пути 5 сек.',
      cooldown: 26,
      duration: 5,
    },
  },
};

export const WEAPON_LIST: WeaponDef[] = Object.values(WEAPONS);

/** Weapon every player starts with. */
export const STARTING_WEAPON: WeaponId = 'sharpenedStick';

/** Per-weapon-level stat multipliers applied to damage / magazine. */
export const WEAPON_LEVEL_SCALING = {
  damagePerLevel: 0.15, // +15% damage per level above 1
  magazinePerLevel: 0.1, // +10% magazine per level above 1
  reloadPerLevel: 0.05, // -5% reload time per level above 1
} as const;

/**
 * Resource cost to upgrade a weapon from `level` to `level + 1`.
 * Scales the base cost by `costGrowth ^ (level - 1)`. Returns null at max level.
 */
export function weaponUpgradeCost(
  def: WeaponDef,
  level: number,
): Partial<Record<import('@/types').ResourceType, number>> | null {
  if (level >= def.maxLevel) return null;
  const factor = Math.pow(def.costGrowth, level - 1);
  const out: Partial<Record<import('@/types').ResourceType, number>> = {};
  for (const [k, v] of Object.entries(def.upgradeBaseCost) as [
    import('@/types').ResourceType,
    number,
  ][]) {
    out[k] = Math.round(v * factor);
  }
  return out;
}

/** Returns the effective stats for a weapon at a given upgrade level. */
export function weaponStatsAtLevel(def: WeaponDef, level: number) {
  const l = Math.max(1, level) - 1;
  return {
    damage: def.damage * (1 + WEAPON_LEVEL_SCALING.damagePerLevel * l),
    magazine: Math.round(def.magazine * (1 + WEAPON_LEVEL_SCALING.magazinePerLevel * l)),
    reloadTime: def.reloadTime * (1 - WEAPON_LEVEL_SCALING.reloadPerLevel * l),
    fireRate: def.fireRate,
    range: def.range,
  };
}
